name: Chromatic

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-and-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Project
        uses: ./.github/actions/setup

      - name: Run Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          autoAcceptChanges: "main"
          exitOnceUploaded: true
          exitZeroOnChanges: true
