name: Chromatic

on:
  push:
    branches: [main]
  pull_request:

jobs:
  chromatic:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: ui
            path: packages/ui
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Project
        uses: ./.github/actions/setup

      - name: Build Storybook for ${{ matrix.package }}
        run: pnpm run build-storybook:${{ matrix.package }} --webpack-stats-json

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: ${{ matrix.path }}/storybook-static
          onlyChanged: true
          autoAcceptChanges: "main"
          exitOnceUploaded: true
          exitZeroOnChanges: true
